config/routes.rb
SimplyBetter::Application.routes.draw do

  get 'ping' => 'application#ping'

  resources :landing_page, only: :index do
    post :contact_us, on: :collection
  end

  namespace :widget_api do
    resources :ideas, except: [:new, :edit] do
      resources :comments, only: [:create, :index, :update], format: :json
      get :find_similar, on: :collection
    end
    resources :votes, only: [] do
      get :cast, on: :collection
      post :cast, on: :collection
    end
    resources :applications, only: [], param: :token do
      get :client_js, on: :collection
      get :is_admin, on: :member
    end
    resources :notifications, only: [:index, :update] do
      get :count, on: :collection
    end
    resources :faqs
    resource :user, only: [:show, :update]
    resource :email_settings, only: [:show, :update]
    resources :support_messages, only: [:create]
  end

  resources :customers, only: [:index, :new, :create, :edit, :update] do
    member do
      get :edit_unsafe
      put :update_unsafe
      patch :update_unsafe
    end
  end

  resources :applications, except: [:destroy, :edit] do
    get :preview, on: :member
    get :show_ideas, on: :member
    get :installation_instructions, on: :member
    get :customization, on: :member
    resources :collaborators, only: [:index, :create, :destroy]
    resources :ideas, only: [:index, :update, :destroy]
    resources :faqs
  end

  resources :email_settings, param: :unsubscribe_token, only: [] do
    get :unsubscribe, on: :member
  end

  resources :password_resets, only: [:new, :create, :edit, :update] do
    get :check_email, on: :collection
  end

  get 'widget' => 'widget#widget'

  resource :sessions, only: [], path: '', as: '' do
    get :login, action: :new
    get :popup_login, action: :popup_new
    get :popup_close
    post :create, path: 'sessions/create'
    post :popup_create, path: 'sessions/popup_create'
    delete :destroy, path: 'sessions/destroy', as: 'sign_out'
  end

  resource :reports, only: [] do
    get :overview
  end

  root 'landing_page#index'
end

app/views/shared/_alert_success.html.haml
- unless notice.blank?
  .alert.alert-success.alert-dismissable
    = notice
    %button.close{type: 'button', 'data-dismiss' => 'alert', 'aria-hidden' => 'true'}
      &times;

app/views/shared/_alerts.html.haml
- if flash[:notice]
  .alert.alert-success.alert-dissmissable
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
    %strong Success!
    = flash[:notice]
- if flash[:error]
  .alert.alert-danger.alert-dismissable
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
    %strong Oh snap!
    = flash[:error]
- if flash[:alert] || model.errors.any?
  .alert.alert-danger.alert-dismissable
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
    %strong Oh snap!
    = flash[:alert]
    - model.errors.full_messages.each do |msg|
      %p
        \-
        = msg

app/views/shared/_demo_widget.html.haml
:javascript
  var _smplyBtr = _smplyBtr || {};
  _smplyBtr.appKey = 'DEMO';
  _smplyBtr.email = "demo@simplybetter.io";
  _smplyBtr.name = "Guest user" ;
  (function() {
  var sb = document.createElement('script'); sb.type = 'text/javascript'; sb.async = true; sb.src = "#{WidgetPath.path}/widget_api/applications/client_js.js?appkey="+_smplyBtr.appKey; var s = document.getElementsByTagName('body')[0]; s.appendChild(sb);
  })();

app/views/shared/_email_footer.html.haml
.unsubscribe
  Don't want email notifications?
  = link_to unsubscribe_email_setting_url(@receiver.email_setting.unsubscribe_token) do
    Unsubscribe

app/views/shared/_email_header.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    = stylesheet_link_tag  'email'

app/views/shared/_email_idea.html.haml
.idea-layout
  .idea-item
    %hr
    %h1
      = @idea.title
    %p.desc.ideaView
      = @idea.description
    .comments
      - @idea.comments.each do |comment|
        %p
          %strong= "#{comment.creator.name}:"
          = comment.body
    %hr

app/views/shared/_google_analytics_main.html.haml
- if defined?(landing_page)
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-27828405-4', 'auto');
    ga('send', 'pageview');
- else
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-27828405-2', 'auto');
    ga('send', 'pageview');

app/views/shared/_google_analytics_widget.html.haml
:javascript
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-27828405-3', 'auto');
  ga('send', 'pageview');

app/views/shared/_navbar.html.haml
#navbar
  .col-xs-12
    %h1
      = @application.name
      - if @application.disabled?
        = link_to customization_application_path(@application.id, anchor: 'disabled') do
          %span(style='font-size: 16px')
            %span.label.label-default
              %span.glyphicon.glyphicon-ban-circle
              &nbsp;disabled
    .links
      = link_to installation_instructions_application_path(@application.id) do
        Installation instructions
      = link_to show_ideas_application_path(@application.id) do
        Show ideas
      = link_to customization_application_path(@application.id) do
        Customization
      - unless @application.disabled
        = link_to preview_application_path(@application.id) do
          My widget
      - if @application.faqs_enabled
        = link_to application_faqs_path(@application.id) do
          FAQ
      = link_to application_collaborators_path(@application.id) do
        Collaborators

app/views/shared/_navbar_account_settings.html.haml
#navbar
  .col-xs-12
    %h1 My Account
    .links
      = link_to edit_customer_path do
        Personal information
      = link_to edit_unsafe_customer_path do
        Change password
      = link_to sign_out_path, method: :delete do
        Sign out

app/views/shared/_sidebar.html.haml
.col-xs-12
  .new-application
    = link_to 'New project', new_application_path, class: 'button-new'
  .links
    %h3
      Projects
    - unless applications.blank?
      - applications.each do |a|
        =link_to show_ideas_application_path(a.id) do
          .row{class: active(a)}
            .col-xs-10.name
              =a.name
            .col-xs-2.info
              %span.badge.pull-right
                - if a.disabled?
                  %span.glyphicon.glyphicon-ban-circle(style='font-size: 16px')
                - else
                  =a.ideas.count
    - else
      You have not created any projects (widgets for your website) yet

    - if current_customer.superadmin?
      %h3 Admin
      = link_to overview_reports_url do
        .row
          .col-xs-10.name
            Statistics

.bottom
  .support
    %a.simplybetterSupportButton
      Need support?
  .user
    = current_customer.name
    |
    = link_to "Sign out", sign_out_path, class: 'navbar-link', method: :delete

app/views/shared/_social_meta.html.haml
/ Social tags
- title = 'Ideas and Innovation Management App | SimplyBetter.io'
- desc = 'SimplyBetter is an Ideas and Innovation management app for user-driven Product Development success. Allow your users to improve your product. Learn more..'
- img = 'images/simplybetter.png'

%meta{content:  title, itemprop:  'name'}
%meta{content:  desc, itemprop:  'description'}
%meta{content:  img, itemprop:  'image'}
/ Twitter Card data
%meta{content:  title, name: 'twitter:title'}
%meta{content:  desc, name: 'twitter:description'}
%meta{content:  img, name: 'twitter:image'}
/ Open Graph data
%meta{content:  title, property:  'og:title'}/
%meta{content:  'http://simplybetter.io/', property:  'og:url'}
%meta{content:  desc, property:  'og:description'}/
%meta{content:  'SimplyBetter', property:  'og:site_name'}
%meta{content:  img, property:  'og:image'}

app/views/shared/_widget.html.haml
:javascript
  var _smplyBtr = _smplyBtr || {};
  _smplyBtr.appKey = 'BYGKGJYA';
  _smplyBtr.email = "#{current_customer.try(:email)}";
  _smplyBtr.name = "#{current_customer.try(:name)}" ;
  (function() {
  var sb = document.createElement('script'); sb.type = 'text/javascript'; sb.async = true; sb.src = "#{WidgetPath.path}/widget_api/applications/client_js.js?appkey="+_smplyBtr.appKey; var s = document.getElementsByTagName('body')[0]; s.appendChild(sb);
  })();