config/routes.rb
SimplyBetter::Application.routes.draw do

  get 'ping' => 'application#ping'

  resources :landing_page, only: :index do
    post :contact_us, on: :collection
  end

  namespace :widget_api do
    resources :ideas, except: [:new, :edit] do
      resources :comments, only: [:create, :index, :update], format: :json
      get :find_similar, on: :collection
    end
    resources :votes, only: [] do
      get :cast, on: :collection
      post :cast, on: :collection
    end
    resources :applications, only: [], param: :token do
      get :client_js, on: :collection
      get :is_admin, on: :member
    end
    resources :notifications, only: [:index, :update] do
      get :count, on: :collection
    end
    resources :faqs
    resource :user, only: [:show, :update]
    resource :email_settings, only: [:show, :update]
    resources :support_messages, only: [:create]
  end

  resources :customers, only: [:index, :new, :create, :edit, :update] do
    member do
      get :edit_unsafe
      put :update_unsafe
      patch :update_unsafe
    end
  end

  resources :applications, except: [:destroy, :edit] do
    get :preview, on: :member
    get :show_ideas, on: :member
    get :installation_instructions, on: :member
    get :customization, on: :member
    resources :collaborators, only: [:index, :create, :destroy]
    resources :ideas, only: [:index, :update, :destroy]
    resources :faqs
  end

  resources :email_settings, param: :unsubscribe_token, only: [] do
    get :unsubscribe, on: :member
  end

  resources :password_resets, only: [:new, :create, :edit, :update] do
    get :check_email, on: :collection
  end

  get 'widget' => 'widget#widget'

  resource :sessions, only: [], path: '', as: '' do
    get :login, action: :new
    get :popup_login, action: :popup_new
    get :popup_close
    post :create, path: 'sessions/create'
    post :popup_create, path: 'sessions/popup_create'
    delete :destroy, path: 'sessions/destroy', as: 'sign_out'
  end

  resource :reports, only: [] do
    get :overview
  end

  root 'landing_page#index'
end

app/models/application.rb
class Application < ActiveRecord::Base
  extend Enumerize
  has_paper_trail
  belongs_to :price_plan
  has_and_belongs_to_many :customers
  has_and_belongs_to_many :users, join_table: 'widget_users'
  has_and_belongs_to_many :widget_customers, class_name: 'Customer', join_table: 'widget_customers'
  belongs_to :owner, class_name: 'Customer',
                     foreign_key: 'customer_id'

  has_many :support_messages

  has_many :ideas, -> { order('votes_count DESC') }
  has_many :comments, -> { order('comments.votes_count DESC') }, through: :ideas
  has_many :notifications
  has_many :faqs

  enumerize :icon, in: [:triangle, :circle, :none], default: :triangle

  validates_uniqueness_of :token
  validates_presence_of :name, :owner

  validates :support_email,
            format: EmailValidator.validator,
            if: -> { support_email_changed? && (support_email.blank? ? (self.support_email = nil) : true)}
            # length TODO: OMA: er offline. husker ikke hvordan man validerer lengde hvis satt, minimum 1 tegn.
            # nil skal her være godtatt og empty skal bli nil. Sorry, får det ikke til :)

  before_create :generate_token

  scope :active, -> { where(disabled: false) }
  scope :disabled, -> { where(disabled: true) }
  scope :with_engaged_users, -> { all.select { |a| a.engaged_users } }


  delegate :price, to: :price_plan

  def support_emails
    support_email || customers.map(&:email).join(',')
  end

  # List users that has engaged in the widget
  # By writing an idea, commenting, voting or sending a support message
  def engaged_users
    self.users.select { |u| u.ideas.count > 0 || u.comments.count > 0 || u.votes.count > 0 || u.support_messages.count > 0 }
  end

  private

  def generate_token
    self.token = (0...8).map{(65+rand(26)).chr}.join
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protect_from_forgery with: :null_session, :if => Proc.new { |c| c.request.format == 'application/json' }
  before_filter :set_controller_and_action_names

  before_filter :set_new_relic if Rails.env == 'production' || Rails.env == 'staging'

  include CurrentCustomer

  def ping
    render text: "What's crackin' newrelic?"
  end

  private

  helper_method :current_customer

  def applications
    @applications ||= current_customer.applications.to_a.delete_if{|a| a.new_record?} if current_customer
  end
  helper_method :applications

  def authorize
    redirect_to_login unless current_customer
  end

  def authorize_superadmin
    authorize and return unless current_customer
    redirect_to_applications unless current_customer.superadmin?
  end

  def set_controller_and_action_names
    @current_controller = controller_name
    @current_action     = action_name
  end

  def set_new_relic
    puts "params is #{params}"
    ::NewRelic::Agent.add_custom_parameters(
        params: params
    )
  end

  private

  def redirect_to_login
    respond_to do |format|
      format.html { redirect_to login_url, alert: "Not authorized" }
      format.json { render json: { message: 'Not authorized' }, status: :unauthorized}
    end
  end

  def redirect_to_applications
    respond_to do |format|
      format.html { redirect_to applications_url, alert: "You are not authorized" }
    end
  end

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :authorize
  before_action :set_application, only: [:show_ideas, :installation_instructions, :show, :update, :preview, :customization]

  def index
    if applications.any?
      redirect_to show_ideas_application_path(applications.first.id)
    else
      redirect_to new_application_path
    end
  end

  def new
    @application = Application.new
    @application.price_plan = PricePlan.find_by_id(cookies[:price_plan])
  end

  def show
  end

  def customization
  end

  def show_ideas
  end

  def installation_instructions
  end

  def update
    @application.update_attributes!(application_attributes)
  rescue ActiveRecord::RecordInvalid
    render json: { errors: @application.errors.full_messages }, status: 400
  end

  def create
    @application = Application.new(application_attributes)
    @application.owner = current_customer
    @application.customers << current_customer
    if @application.save
      cookies.delete(:price_plan)
      redirect_to customization_application_path(@application.id)
    else
      render :new
    end
  end

  def preview
    if @application.disabled
      redirect_to show_ideas_application_path(@application.id), alert: 'This applications is disabled'
    end
    @token = @application.token
    @email = current_customer.email
    @name = current_customer.name
  end

  private

  def set_application
    if params[:id]
      @application ||= current_customer.applications.find(params[:id])
      session[:current_application] = @application.id
    end
  rescue
    flash[:error] = "We couldn't find that application, or you don't have rights to that application"
    redirect_to edit_customer_path
  end

  def application_attributes
    params.require(:application).permit(:name, :intro, :icon, :support_enabled, :support_email, :third_party_support, :faqs_enabled, :price_plan_id, :disabled)
  end
end

app/controllers/widget_api/applications_controller.rb
class WidgetApi::ApplicationsController < ApplicationController
  protect_from_forgery except: :client_js
  respond_to :json, :html

  def client_js
    expires_in 20.minutes
    if (app = Application.active.find_by(token: params[:appkey]))
      @icon = app.icon
    else
      @error = "Could not find application with appkey #{params[:appkey]}"
    end
  end

  def is_admin
    answer = current_customer && current_customer.applications.active.find_by(token: params[:token])
    render json: { is_admin: !!answer }.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_error_class(model_object, field)
    'has-error' if model_object.errors.messages[field]
  end

  def active(app)
    return unless @application
    'active' if app.id == @application.id
  end

  def percent_of_total(total, selection)
    "#{number_with_precision( (selection.to_f / total.to_f) * 100, precision: 0 )}%"
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
  def price_plans
    PricePlan.plans_select
  end
end

app/views/application/_form.html.haml
.application_form
  .row
    .col-lg-5
      %h2 Name and intro
      %label(for="application_name") Name
      %input#application_name(type="text" placeholder="Project name (ie your website name)" ng-model="application.name" required)
      %label(for="application_intro") Introduction
      %textarea#application_intro(ng-model="application.intro")

  .row
    .col-lg-5
      %h2 Price plan
      %select(ng-options='plan[1] as plan[0] for plan in application.priceplans' ng-model='application.price_plan_id')

      = render 'shared/promo_codes.html.haml/promo_codes'

      #disabled.checkbox
        %label
          %input#disable-app(type='checkbox' ng-model="application.disabled")
          Disable application
        %p Disabled application will not be charged and the widget will not work anymore

  .row
    .col-lg-5
      %h2 Support
      .checkbox
        %label(for="application_support")
          %input#application_support(type="checkbox" ng-model="application.support_enabled")
          Enable Support
        %p
          Enables a new icon where users can post support requests to you email account (or a custom email).
          %a(ng-click="toggleSupportHelp()") Read more
      %input(type="text" ng-model="application.support_email" placeholder="default: {{ application.support_emails }}" ng-if="application.support_enabled")

      .read-more(ng-click="toggleSupportHelp()" ng-class="{ active: supportHelp }" ng-show="supportHelp")
        .arrow

    .col-lg-7
      .help-button-padding(ng-show="supportHelp")
        %h3 Enable Support
        %p
          When you check the support button. A button will appear on the side of the widget. This button will take users to a form where they can submit support requests.
          %br
          By default a support request will be sendt to all collaborators emails, if you want to use a custom email you can simply provide a new email in the input field (this field appears after you enables support.)
        %h3 Your own support button
        %p
          You can add your own custom support button. This button will open the widget and navigate to the support page. Just assign the class .simplybetterSupportButton to any html tag.
        %pre
          %code
            =preserve do
              :escaped
                <button class="simplybetterSupportButton">Support</button>

  .row
    .col-lg-5
      .checkbox
        %label
          %input(type="checkbox" ng-model="application.third_party_support")
          Trigger my existing support service
        %p
          When clicked it will trigger window.simplyBetterSupportClick(), so make sure you implement this function and make it trigger whatever you want it to trigger on your site. You can read more about this
          %a(ng-click="toggleSupportHelp2()") here

      .read-more(ng-click="toggleSupportHelp2()" ng-class="{ active: supportHelp2 }" ng-show="supportHelp2")
        .arrow

    .col-lg-7
      .help-button-padding(ng-show="supportHelp2")
        %h2#support-custom-handle
          Trigger existing support service
        %p
          If "Trigger my existing support service" has been checked, you will be able to trigger your own support service by implementing the following javascript function in your code:
        %pre
          %code
            = preserve do
              :escaped
                window.simplyBetterSupportClick = function () {
                  // Trigger my support service
                }
        %p
          This is useful if you use a third party support service, or if you have implemented your own and wish to direct simplybetter users to this service.


  .row
    .col-lg-5
      %h2 Faq
      .checkbox
        %label
          %input(type="checkbox" ng-model="application.faqs_enabled")
          Enable FAQ

  .row
    .col-lg-5
      .errors(ng-if="errors")
        %h3 The following errors prevented us from saving:
        .error(ng-repeat="error in errors")
          %span.glyphicon.glyphicon-remove
            {{ error }}

      %button#customization-save(ng-click="customize.save()" ng-disabled="customize.isUnchanged() || !form.$valid")
        {{ customize.saveText }}
        %span.glyphicon.glyphicon-ok(ng-if="customize.hasJustBeenSaved()")

app/views/application/_idea_unit.html.haml
.list-group-item{id: "idea_#{f.id}"}
  .row
    .col-xs-12
      %h4.list-group-item-heading= f.title
      %p.list-group-item-text= truncate(f.description, length: 100)
  .row
    .col-xs-12
      %table
        %tr
          %td.meta.upvotes
            #{f.upvotes}
            %i.fa.fa-thumbs-o-up
          %td.meta.downvotes
            #{f.downvotes}
            %i.fa.fa-thumbs-o-down
          %td.meta.comments-toggle
            #{f.comments.count} comments
          %td.meta
            Created by #{f.creator.name}, on #{f.created_at.strftime("%d/%m/%y")}
  .row#comments
    .col-xs-12
      .comments-section
        %ol
          - f.comments.each do |c|
            %li.comment-item
              .avatar
                = image_tag c.creator.gravatar_url
              .content
                %span.username= c.creator.name
                on
                %span= c.created_at.strftime("%d/%m/%y")
                .comment-body
                  = c.body
              .clear
  .switch-list
    = link_to send(path, @application.id,f),
      remote: true,
      title: "Move idea",
      method: method do
      - if method == :post
        %i.fa.fa-arrow-left
      - else
        %i.fa.fa-arrow-right
  .edit-panel
    = link_to edit_application_idea_path(@application.id, f.id) do
      %i.fa.fa-edit
    = link_to application_idea_path(@application.id, f.id), method: :delete, confirm: "Are you sure?" do
      %i.fa.fa-times

  .clear

app/views/application/_instalation_instructions.html.haml
%h2 Add this code to your website
%ul
  %li
    First you have to copy the snippet below and paste it anywhere inside your &lt;body&gt; tag.
  %li
    Replace "INSERT EMAIL HERE" with the signed in user's email address.
    In a rails app this would typically be \#{current_user.email}. Do the same with the users name or nickname!
/ Nav tabs
%ul.nav.nav-tabs
  %li.active
    %a{"data-toggle" => "tab", href: "#other"} HTML
  %li
    %a{"data-toggle" => "tab", href: "#rails"} Rails + Devise (erb)
  %li
    %a{"data-toggle" => "tab", href: "#rails_haml"} Rails + Devise (haml)
/ Tab panes
.tab-content
  #other.fade.tab-pane.active.in
    %pre.copy-code
      %code
        = preserve do
          :escaped
            <!-- Paste at the BOTTOM of BODY -->
            <script>
                var _smplyBtr = _smplyBtr || {};
                _smplyBtr.email = "<INSERT EMAIL HERE>";
                _smplyBtr.name = "<INSERT NAME HERE>" ;

                _smplyBtr.appKey = "#{@application.token}";
                (function() {
                    var sb = document.createElement('script');
                    sb.type = 'text/javascript';
                    sb.async = true;
                    sb.src = "#{WidgetPath.path}/widget_api/applications/client_js.js?appkey="+_smplyBtr.appKey;
                    var s = document.getElementsByTagName('body')[0];
                    s.appendChild(sb);
                })();
            </script>
  #rails.fade.tab-pane
    %pre.copy-code
      %code
        = preserve do
          :escaped
            <!-- Paste at the BOTTOM of BODY -->
            <% if user_signed_in? && Rails.env.production? %>
              <script>
                  var _smplyBtr = _smplyBtr || {};
                  _smplyBtr.email = "<%= current_user.email %>";
                  _smplyBtr.name = "<%= current_user.name %>" ;

                  _smplyBtr.appKey = "#{@application.token}";
                  (function() {
                      var sb = document.createElement('script');
                      sb.type = 'text/javascript';
                      sb.async = true;
                      sb.src = "#{WidgetPath.path}/widget_api/applications/client_js.js?appkey="+_smplyBtr.appKey;
                      var s = document.getElementsByTagName('body')[0];
                      s.appendChild(sb);
                  })();
              </script>
            <% end %>
  #rails_haml.fade.tab-pane
    %pre.copy-code
      %code
        = preserve do
          :escaped
            / Paste at the BOTTOM of BODY
            - if user_signed_in? && Rails.env.production?
              :javascript
                var _smplyBtr = _smplyBtr || {};
                _smplyBtr.email = "\#{current_user.email}";
                _smplyBtr.name = "\#{current_user.name}";

                _smplyBtr.appKey = "#{@application.token}";
                (function() {
                    var sb = document.createElement('script');
                    sb.type = 'text/javascript';
                    sb.async = true;
                    sb.src = "#{WidgetPath.path}/widget_api/applications/client_js.js?appkey="+_smplyBtr.appKey;
                    var s = document.getElementsByTagName('body')[0];
                    s.appendChild(sb);
                })();

app/views/application/_select_icon.html.haml
.row
  .col-lg-5
    %h2 Select icon style
    %p
      You can change the icon whenever you want. There is also some
      %a(ng-click="toggleIconHelp()") optional advanced icon options
    .box.with-form
      .col-xs-12.icon_select
        %table
          %tr
            %td(ng-repeat="icon in application.icons")
              %label(ng-class="{ selected: application.icon == icon }" for="application_icon_{{icon}}")
                %input(id="application_icon_{{icon}}" type='radio' name="icon" ng-model="application.icon" ng-value="icon")
                .icon(ng-class="icon")
    %p
      Read more about the "No icon" option
      %a(ng-click="toggleIconHelp()") here

    .read-more(ng-click="toggleIconHelp()" ng-class="{active: iconHelp}" ng-show="iconHelp")
      .arrow

  .col-lg-7
    .help-button-padding(ng-show="iconHelp")
      %h2#custom-icon Advanced customization of icon (optional)
      %p
        It's really easy to style the icon if you want to.
        You can override the css so you'll have complete control. Below is the current
        styling for the triangle-call-for-action icon. You can override any property by using !important.

      %pre
        %code
          = preserve do
            :escaped
              #simplybetterActivateButton {
                position: fixed;
                right: -75px;
                bottom: -75px;
                height: 150px;
                width: 150px;
                z-index: 2000;
                background: url('/lightbulb_triangle.gif') no-repeat;
                background-size: contain;
                transform:rotate(45deg);
                -ms-transform:rotate(45deg); /* IE 9 */
                -webkit-transform:rotate(45deg); /* Safari and Chrome */

                &:hover{
                  cursor: pointer;
                }
              }

      %h3 Example: Moving the triangle to the left side
      %pre
        %code
          = preserve do
            :escaped
              #simplybetterActivateButton{
                left: -75px !important;
                transform: rotate(135deg) !important;
                -ms-transform: rotate(135deg) !important;
                -webkit-transform: rotate(135deg) !important;
              }

      %h2#no-icon I want to use my own link/icon to trigger simplybetter
      %p
        Select the "no icon" in the icon selector box. Now all you have to do is assign the css class ".simplybetterActivateButton" to any element you want(See example below), and the widget will open on click
      %pre
        %code
          = preserve do
            :escaped
              <button class="simplybetterActivateButton">Ideas?</button>

      %h3 What about the notifications?
      %p
        When "No icon" is selcted, the notifications are hidden by default. If you wish to display them, you can override the css like in the example below
      %pre
        %code
          = preserve do
            :escaped
              .simplybetterActivateButton {
                span {
                  display: fixed !important;
                  // Styling of your choice
                }
              }

app/views/application/abuse_reports_page.html.haml
=render 'shared/navbar'
#abuse-reports.col-xs-12(ng-controller='abuseReportsCtrl as reports' ng-init="init(#{@application.id})")
  %h1 Reported items
  %list-reports

app/views/application/administrate.html.haml
.applications
  =render 'sidebar'

.col-md-8
  %h1
    How to set up the client application code
  %ul
    %li
      First you have to copy the snippet below and paste it anywhere inside your &lt;body&gt; tag.
    %li
      When this is done, you have to replace "INSERT EMAIL HERE" with the signed in user's email address.
      In a rails app this would typically be \#{current_user.email}. Do the same with the users name or nickname!
  %textarea.col-md-12{rows: 10}
    <script>
    var _smplyBtr = _smplyBtr || {};
    _smplyBtr.email = "<INSERT EMAIL HERE>";
    _smplyBtr.name = "<INSERT NAME HERE>" ;

    _smplyBtr.appKey = "#{@application.token}";
    (function() {
    var sb = document.createElement('script'); sb.type = 'text/javascript'; sb.async = true; sb.src = 'http://simplybetter.io/assets/widget-client.js.erb'; var s = document.getElementsByTagName('body')[0]; s.appendChild(sb);
    })();
    </script>

app/views/application/administrate_group.html.haml
=render 'shared/navbar'
.col-xs-12
  = render 'shared/alerts', model: current_customer
  #manage-ideas(ng-controller='IdeaFilterCtrl')
    %div.ideas-navigate
      %a(href='#' ng-click='showAll()' ng-class='{ active: activeClass == "all" }' ) All
      %a(href='#' ng-click='hideCompleted()' ng-class='{ active: activeClass == "hide_completed" }') Not completed
      %a(href='#' ng-click='showCompleted()' ng-class='{ active: activeClass == "completed"}') Completed
      %a(href='#' ng-click='showVisible()' ng-class='{ active: activeClass == "visible" }') Visible
      %a(href='#' ng-click='hideVisible()' ng-class='{ active: activeClass == "hide_visible" }') Hidden
    %ul(ng-controller='ideaCtrl' ng-init="init('#{@application.id}')")
      %li.idea(ng-repeat='idea in ideas | filter:selectedFilter' ng-class='{ "completed": idea.completed}')
        %div(ng-if='idea.$edit')
          .error(ng-if='error_message')
            {{ error_message }}
          %form(name='editIdea' novalidate)
            %input(type='text' name='title' value='{{idea.title}}' ng-model='idea.title' required)
            %textarea(name='description' ng-model='idea.description')
              {{ idea.description }}
              {{ editIdea }}
            %button.btn(ng-click='save(idea)' ng-class='{ disabled: !editIdea.$dirty || editIdea.$invalid }') Save
            %button.btn(ng-click='cancel(idea)') Cancel
        %div(ng-if='!idea.$edit')
          %h1
            {{ idea.title }}
          %p
            {{ idea.description }}
          .meta
            .icon.upvote
            %span.upvotes
              {{ idea.upvotes }}
            %span.dot •
            .icon.downvote
            %span.downvotes
              {{ idea.downvotes }}
            %span.dot •
            .icon.comment
            %span.comment(ng-click='idea.$show_comments = !idea.$show_comments')
              {{ idea.comments_count }} comments
            %span.dot •
            by
            %span.user
              %span
                {{ idea.creator_name }}
            on
            %span.time
              {{ idea.updated_at }}
          .not-visible-overlay(ng-if='!idea.visible')
          %options(item='idea' admin='true' all='true' togglevisible='toggleVisible(idea)' togglecompleted='toggleCompleted(idea)' edititem='edit(idea)' deleteitem='delete(idea, $index)')
          .comments(ng-if='idea.$show_comments')
            %ul
              %li.comment-item(ng-repeat='comment in idea.comments')
                .avatar
                  %img(ng-src='{{comment.gravatar_url}}')
                .content
                  .meta
                    %span.username
                      {{ comment.creator_name }}
                    %span on
                    %span
                      {{ comment.updated_at }}
                  .comment-body
                    {{ comment.body }}
                  .not-visible-overlay(ng-if='!comment.visible')
                  .options
                    .icon(ng-class='{ visible: comment.visible, "not-visible": !comment.visible }' ng-click='toggleVisibleComment(comment)')

app/views/application/collaborators.html.haml
=render 'shared/navbar'

.collaborators(ng-controller="CollaboratorsCtrl as collaborator")
  .col-lg-8
    %h3
      Collaborators
  .col-lg-4
    %button(type='submit' ng-click="visible = true")
      Add collaborator
  .col-lg-12
    %table.table
      %tr(ng-repeat="customer in collaborator.list")
        %td.narrow
          %img.round(ng-src="{{customer.gravatar_url}}")
        %td
          {{ customer.name }}
        %td
          {{ customer.email }}
        %td
          {{ collaborator.ownerOrCollaborator(customer) }}
        %td.narrow
          .icon.delete(ng-hide="customer.is_me" yes-no-prompt="" yes="collaborator.remove(customer)" text="'Are you sure you want to remove ' + customer.name + '?'")


  %modal(visible="visible")
    %h3 New collaborator
    %label Name
    %input(type='text' placeholder='John Doe' ng-model='collaborator.name')
    %label Email Address
    %input(type='email' placeholder='user@domain.com' ng-model='collaborator.email')
    %button(type='submit' ng-click='collaborator.invite()')
      Add collaborator

app/views/application/customization.html.haml
=render 'shared/navbar'
#customize.col-lg-12(ng-controller="customizationCtrl as customize")
  %form(name="form" novalidate)
    = render 'application/select_icon'
    = render 'application/form'

app/views/application/index.html.haml
=render 'shared/navbar'
.col-md-12
  =render 'shared/alert_success', notice: notice
.col-md-12
  .panel.panel-success
    .panel-heading
      %h3.panel-title
        Create a new application!
    .panel-body
      = form_for @application,html: {class: "form-horizontal", role: "form"} do |f|
        - if @application.errors.any?
          .alert.alert-danger
            %p
              %strong
                Unfortunately some errors prevented you from creating the application:
            %ul
              - @application.errors.full_messages.each do |msg|
                %li= msg
        .form-group
          %label.col-md-4.control-label New application name
          .col-md-8
            = f.text_field :name, class: 'form-control'
        .form-group
          .col-md-offset-4.col-md-8
            = f.button 'Create application', class: 'btn btn-default'

app/views/application/installation_instructions.html.haml
=render 'shared/navbar'
.col-lg-12
  %h2 Add this code to your website
  %ul
    %li
      First you have to copy the snippet below and paste it anywhere inside your &lt;body&gt; tag.
    %li
      Replace "INSERT EMAIL HERE" with the signed in user's email address.
      In a rails app this would typically be \#{current_user.email}. Do the same with the users name or nickname!
  / Nav tabs
  %ul.nav.nav-tabs
    %li.active
      %a{"data-toggle" => "tab", href: "#other"} HTML
    %li
      %a{"data-toggle" => "tab", href: "#rails"} Rails + Devise (erb)
    %li
      %a{"data-toggle" => "tab", href: "#rails_haml"} Rails + Devise (haml)
  / Tab panes
  .tab-content
    #other.fade.tab-pane.active.in
      %pre.copy-code
        %code
          = preserve do
            :escaped
              <!-- Paste at the BOTTOM of BODY -->
              <script>
                  var _smplyBtr = _smplyBtr || {};
                  _smplyBtr.email = "<INSERT EMAIL HERE>";
                  _smplyBtr.name = "<INSERT NAME HERE>" ;

                  _smplyBtr.appKey = "#{@application.token}";
                  (function() {
                      var sb = document.createElement('script');
                      sb.type = 'text/javascript';
                      sb.async = true;
                      sb.src = "#{WidgetPath.path}/widget_api/applications/client_js.js?appkey="+_smplyBtr.appKey;
                      var s = document.getElementsByTagName('body')[0];
                      s.appendChild(sb);
                  })();
              </script>
    #rails.fade.tab-pane
      %pre.copy-code
        %code
          = preserve do
            :escaped
              <!-- Paste at the BOTTOM of BODY -->
              <% if user_signed_in? && Rails.env.production? %>
                <script>
                    var _smplyBtr = _smplyBtr || {};
                    _smplyBtr.email = "<%= current_user.email %>";
                    _smplyBtr.name = "<%= current_user.name %>" ;

                    _smplyBtr.appKey = "#{@application.token}";
                    (function() {
                        var sb = document.createElement('script');
                        sb.type = 'text/javascript';
                        sb.async = true;
                        sb.src = "#{WidgetPath.path}/widget_api/applications/client_js.js?appkey="+_smplyBtr.appKey;
                        var s = document.getElementsByTagName('body')[0];
                        s.appendChild(sb);
                    })();
                </script>
              <% end %>
    #rails_haml.fade.tab-pane
      %pre.copy-code
        %code
          = preserve do
            :escaped
              / Paste at the BOTTOM of BODY
              - if user_signed_in? && Rails.env.production?
                :javascript
                  var _smplyBtr = _smplyBtr || {};
                  _smplyBtr.email = "\#{current_user.email}";
                  _smplyBtr.name = "\#{current_user.name}";

                  _smplyBtr.appKey = "#{@application.token}";
                  (function() {
                      var sb = document.createElement('script');
                      sb.type = 'text/javascript';
                      sb.async = true;
                      sb.src = "#{WidgetPath.path}/widget_api/applications/client_js.js?appkey="+_smplyBtr.appKey;
                      var s = document.getElementsByTagName('body')[0];
                      s.appendChild(sb);
                  })();

  %p
    When you have pasted the snippet you are good to go. Click
    =link_to 'here', customization_application_path(@application.id)
    if you want to customize your widget

app/views/application/preview.html.haml
=render 'shared/navbar'
- encoded_string = Base64.encode64("?appkey=#{ @token }&email=#{ @email }&name='#{ @name }'")
%iframe{ src: "/widget?info=#{encoded_string}" }

app/views/application/show_ideas.html.haml
=render 'shared/navbar'
.col-xs-12
  = render 'shared/alerts', model: current_customer
  %ui-view