config/routes.rb
SimplyBetter::Application.routes.draw do

  get 'ping' => 'application#ping'

  resources :landing_page, only: :index do
    post :contact_us, on: :collection
  end

  namespace :widget_api do
    resources :ideas, except: [:new, :edit] do
      resources :comments, only: [:create, :index, :update], format: :json
      get :find_similar, on: :collection
    end
    resources :votes, only: [] do
      get :cast, on: :collection
      post :cast, on: :collection
    end
    resources :applications, only: [], param: :token do
      get :client_js, on: :collection
      get :is_admin, on: :member
    end
    resources :notifications, only: [:index, :update] do
      get :count, on: :collection
    end
    resources :faqs
    resource :user, only: [:show, :update]
    resource :email_settings, only: [:show, :update]
    resources :support_messages, only: [:create]
  end

  resources :customers, only: [:index, :new, :create, :edit, :update] do
    member do
      get :edit_unsafe
      put :update_unsafe
      patch :update_unsafe
    end
  end

  resources :applications, except: [:destroy, :edit] do
    get :preview, on: :member
    get :show_ideas, on: :member
    get :installation_instructions, on: :member
    get :customization, on: :member
    resources :collaborators, only: [:index, :create, :destroy]
    resources :ideas, only: [:index, :update, :destroy]
    resources :faqs
  end

  resources :email_settings, param: :unsubscribe_token, only: [] do
    get :unsubscribe, on: :member
  end

  resources :password_resets, only: [:new, :create, :edit, :update] do
    get :check_email, on: :collection
  end

  get 'widget' => 'widget#widget'

  resource :sessions, only: [], path: '', as: '' do
    get :login, action: :new
    get :popup_login, action: :popup_new
    get :popup_close
    post :create, path: 'sessions/create'
    post :popup_create, path: 'sessions/popup_create'
    delete :destroy, path: 'sessions/destroy', as: 'sign_out'
  end

  resource :reports, only: [] do
    get :overview
  end

  root 'landing_page#index'
end

app/views/layouts/application.html.haml
!!!
%html(ng-app='Backoffice' ng-strict-di itemscope itemtype="http://schema.org/Product")
  %head
    = render 'shared/social_meta'
    %title SimplyBetter
    = stylesheet_link_tag    "application", media: "all"
    = jquery_include_tag :jquery
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
  %body{class: "#{@current_controller} #{@current_action}"}
    #logo
      .logo
      .name
        Simply Better
      .customer
        = link_to edit_customer_path(current_customer.id) do
          = image_tag current_customer.gravatar_url, class: 'round'
          Account
    #navigation
      = render 'shared/sidebar'

    - if @application.present? && !@application.new_record?
      #content(ng-controller="applicationsCtrl" ng-init="init('#{@application.token}', '#{@current_customer.email}', '#{@application.id}')")
        .discontinued
          = render 'landing_page/discontinued'
        = yield
        %toast
    - else
      #content
        .discontinued
          = render 'landing_page/discontinued'
        = yield

    %toast

    = render 'shared/widget'
    = render 'shared/google_analytics_main' if Rails.env.production?

app/views/layouts/info.html.haml
!!!
%html
  %head
    %title SimplyBetter
    = stylesheet_link_tag    "info", media: "all"
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
  %body
    .dialog
      %img(src="/img/logo.png")
      = yield

    %a(href='/' class='button') GO TO SIMPLYBETTER
    = render 'shared/google_analytics_main' if Rails.env.production?

app/views/layouts/landing_page.html.haml
!!!
%html{itemscope: '', itemtype: 'http://schema.org/Product'}
  %head
    %meta{content: 'text/html; charset=utf-8', 'http-equiv' => 'Content-Type'}
    %meta{content: 'user-scalable=no, initial-scale=1', name: 'viewport'}
    %meta{content: 'telephone=no', name: 'format-detection'}
    = render 'shared/social_meta'
    %meta(name='description' content='SimplyBetter is an Ideas and Innovation management app for user-driven Product Development success. Allow your users to improve your product. Learn more..')
    %title Ideas and Innovation Management App | SimplyBetter.io
    = stylesheet_link_tag    'landing_page', media: 'all'
    = javascript_include_tag 'landing'
    = csrf_meta_tags
    // CrazyEgg snippet
    :javascript
      setTimeout(function(){var a=document.createElement("script");
      var b=document.getElementsByTagName("script")[0];
      a.src=document.location.protocol+"//script.crazyegg.com/pages/scripts/0041/2194.js?"+Math.floor(new Date().getTime()/3600000);
      a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
  %body(ng-app='LandingPage' ng-strict-di)
    .container(ng-init='scroll = 0')
      %span(scroll-position='scroll')
      %header
        .header-content
          .logoBox
            %img.logo{alt: 'Ideas and Innovation Management App SimplyBetter.io', src: 'img/logo.png'}
            %img.sLogo{alt: 'Ideas and Innovation Management App SimplyBetter.io', src: 'img/sLogo.png'}
          .contactBox
            %ul
              = render 'landing_page/navigation_list'
              - if current_customer
                %li.divider-list
                  %a{href: '#', 'ng-click'=>'display_menu = !display_menu'}
                    = image_tag current_customer.gravatar_url, class: 'avatar'
                %li
                  %a(href='#' ng-click='display_menu = !display_menu')
                    %span ▾
                .customer-menu(ng-if='display_menu')
                  %ul
                    %li
                      = link_to applications_path do
                        Dashboard
                    %li
                      = link_to sign_out_path, method: :delete do
                        Sign out
              - else
                %li.divider-list
                  = link_to 'SIGN IN', login_path
                -#%li.last
                -#  = link_to 'GET SIMPLYBETTER', new_customer_path, class: 'contact'
          .clear
      .closing-notification
        = render 'landing_page/discontinued'
      = yield

      = render 'shared/demo_widget'
      = render 'shared/google_analytics_main', landing_page: true if Rails.env.production?

app/views/layouts/splash_screen.html.haml
!!!
%html{itemscope: '', itemtype: 'http://schema.org/Product'}
  %head
    = render 'shared/social_meta'
    -# Todo: Refactor http://davidlesches.com/blog/elegant-titles-and-seo-meta-tags-in-rails
    - if @current_action == 'new'
      - if @current_controller == 'customers'
        %title Register | SimplyBetter - Ideas and Innovation Management App
        %meta(name='description' content='30-day free trial. Use real user data to build your product and improve your product development with SimplyBetter, an Ideas and Innovation management app.')
      - elsif @current_controller == 'sessions'
        %title Login | SimplyBetter - Ideas and Innovation Management App
        %meta(name='description' content='Move from beta to product launch with faster and better iteration. Involve your users in your product development with SimplyBetter, the Ideas and Innovation Management Tool.')
    - else
      %title SimplyBetter

    = stylesheet_link_tag    "application", media: "all"
    = jquery_include_tag :jquery
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
  %body{class: "#{@current_controller} #{@current_action}"}
    #logo
      .logo
      .name
        Simply Better
    .white-box
      = yield

    - unless @current_action == "popup_new" || @current_action == "popup_create"
      = render 'shared/widget'
    = render 'shared/google_analytics_main', landing_page: true if Rails.env.production?

app/views/layouts/widget.html.haml
!!!
%html
  %head
    %title SimplyBetter
    = stylesheet_link_tag    "widget", media: "all"
    = jquery_include_tag :jquery
    = javascript_include_tag "widget"
    = csrf_meta_tags
  %body
    %script

    / ANGULAR HELP
    / Controllers are found in angular/controllers folder
    / Directives are found in angular/widget.js.coffee
    / Templates are found in angular/templates folder
    / Using directives wich are all found in angular/directives with the templates
    #simplybetterIdeasModal(ng-app='Simplybetter' ng-controller='WidgetCtrl' ng-strict-di)
      .logobar
        %a{href: 'http://simplybetter.io', target: '_blank'}
          .logo
          .logo-text Simply Better
        %span(ng-show='signed_in')
          %faqs-button(ng-show="#{@app.faqs_enabled}")
          %support-button(ng-show="#{@app.support_enabled}" third-party="#{@app.third_party_support}")
          %account-settings-button
          %notifications

      #simplybetterNavbar(ng-class='{ overview: !path }' ng-init="app_name='#{@app.name}'")
        %span(ng-if='path')
          %back(ng-click='reset_path()')
        %h2
          {{app_name}}
        %p= @app.intro

        %idea-new(ng-if='!path || newIdea.title.length')

      #simplybetterIdeasModalContent(ui-view stretch-to-fit)
      %toast
    = render 'shared/google_analytics_main' if Rails.env.production?